apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed-service
  namespace: default
spec:
  selector:
    app: udagram-api-feed
  ports:
    - protocol: TCP
      port: 80           # Port exposed by the Service
      targetPort: 8080   # Port exposed by the container
  type: ClusterIP
