apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-service
  namespace: default
spec:
  selector:
    app: udagram-frontend
  ports:
    - protocol: TCP
      port: 80           # Port exposed by the Service
      targetPort: 80   # Port exposed by the container
  type: LoadBalancer
