apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy-service
  namespace: default
spec:
  selector:
    app: udagram-reverseproxy
  ports:
    - protocol: TCP
      port: 80           # Port exposed by the Service
      targetPort: 80   # Port exposed by the container
  type: LoadBalancer
